### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by seannowotny** [atcarter714/UnityH4xx#1]
Hello there, thank you for taking the time to implement List.ToSpan() for Unity!
I found that the performance is almost as good as Array.ToSpan() in build. Awesome job!
Could you please add a license so UnityH4xx can be used in commercial projects? That would be great!

**Comment by atcarter714** [comment]
Yes! I will try to have that done by tonight 🙂🫠

Keep reminding me if I forget! I started a company and I am running around crazy because we are partnering with Unity Technologies for AITK and Arkaen SDK and at the same time trying to negotiate with the bankers so we can afford this big launch haha 😄🫠

Regards,
Aaron Carter
Arkaen Solutions
***@***.***)

On Apr 27, 2023 1:13 PM, Sean Nowotny ***@***.***> wrote:

Hello there, thank you for taking the time to implement List.ToSpan() for Unity!
I found that the performance is almost as good as Array.ToSpan() in build. Awesome job!
Could you please add a license so UnityH4xx can be used in commercial projects? That would be great!

**Comment by atcarter714** [comment]
> Hello there, thank you for taking the time to implement List.ToSpan() for Unity! I found that the performance is almost as good as Array.ToSpan() in build. Awesome job! Could you please add a license so UnityH4xx can be used in commercial projects? That would be great!

Absolutely. Things went great today, and I am so pleased people are finding this code from a good while back and that it's helping people with performance. I may add a bit to it and make a little Roslyn compiler + assembler + linker service to build it! ❤️‍🔥

**Comment by atcarter714** [comment]
@seannowotny Here you are, sir:
https://github.com/atcarter714/UnityH4xx/blob/main/LICENSE.md

And you have my personal blessing, as well! Let me know if you have any questions, ideas, suggestions, etc. And be sure to check out [Game Dev Nerds Community](https://discord.gg/puQpqy8D) and the new AI/ML and game dev company we started called [Arkaen](https://github.com/arkaen-solutions)! I'd love to see you and your friends come chat, hang out and see what other things we are doing! 👀 ❤️‍🔥 

I'm thrilled this is helping someone, finally!

**Comment by seannowotny** [comment]
Thank you! I would join the Discord, but it looks like the invite has already expired.
Good luck with Arkaen, that sounds like a huge project. Would love to hear more about it!

I'll let you know about the project where I'm using UnityH4xx once it has been released 🙂

**Comment by atcarter714** [comment]
Would love to have you join us, my friend, and tell me [in Game Dev Nerds Discord](https://discord.gg/bWfr9r3A) what other .NET Core features or perf/opt tricks might help you (i.e., threading, SIMD math, etc) :-)

https://discord.gg/bWfr9r3A
